version: '3.4'

services:
  bankingwebapi:
    image: ${DOCKER_REGISTRY-}bankingwebapi
    build:
      context: .
      dockerfile: BankingWebApi\Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1

  dockersqlserver:
    image: ${DOCKER_REGISTRY-}dockersqlserver
    build:
      context: .
      dockerfile: DockerSqlServer/Dockerfile
    depends_on:
      - db
